Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/settings/production.py", line 66, in <module>
    include(settings_file, optional(settings_files), scope=locals())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/split_settings/tools.py", line 93, in include
    raise IOError('No such file: {0}'.format(pattern))
OSError: No such file: /etc/tower/settings.py

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 138, in manage
    prepare_env()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 97, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/lib/awx/venv/awx/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/settings/production.py", line 88, in <module>
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No AWX configuration found at /etc/tower/settings.py.
Define the AWX_SETTINGS_FILE environment variable to specify an alternate path.
/usr/bin/launch_awx.sh: line 15: unset: `#!/bin/bash': not a valid identifier
/usr/bin/launch_awx.sh: line 15: unset: `#': not a valid identifier
Error: Cannot open an HTTP server: socket.error reported errno.EACCES (13)
For help, use /usr/local/bin/supervisord -h
